---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ingress-nginx
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      version: 4.11.x
  install:
    crds: Create
    createNamespace: true
  interval: 1h0m0s
  releaseName: ingress-nginx
  targetNamespace: ingress-nginx
  upgrade:
    crds: CreateReplace
